
// 인증서 리스트 초기화
var KICA_CERTLISTEMPTY = '';
KICA_CERTLISTEMPTY += '<div id=\"select-cert-list-area\" class=\"select-cert-list-area\">';
KICA_CERTLISTEMPTY += '<table id=\"divtable\" class=\"js-selrow\" cellpadding=\"0\" cellspacing=\"0\">';
KICA_CERTLISTEMPTY += '<caption></caption>';
KICA_CERTLISTEMPTY += '<colgroup>';
KICA_CERTLISTEMPTY += '<col style=\"width: 25%\" />';
KICA_CERTLISTEMPTY += '<col style=\"width: auto\" />';
KICA_CERTLISTEMPTY += '<col style=\"width: 20%\" />';
KICA_CERTLISTEMPTY += '<col style=\"width: 25%\" />';
KICA_CERTLISTEMPTY += '</colgroup>';
KICA_CERTLISTEMPTY += '<thead>';
KICA_CERTLISTEMPTY += '<tr>';
KICA_CERTLISTEMPTY += '<th scope=\"col\">';
KICA_CERTLISTEMPTY += '<div>' + NX_WEBUI_LIST_INIT_TEXT_1 + '</div>';
KICA_CERTLISTEMPTY += '</th>';
KICA_CERTLISTEMPTY += '<th scope=\"col\">';
KICA_CERTLISTEMPTY += '<div>' + NX_WEBUI_LIST_INIT_TEXT_2 + '</div>';
KICA_CERTLISTEMPTY += '</th>';
KICA_CERTLISTEMPTY += '<th scope=\"col\">';
KICA_CERTLISTEMPTY += '<div>' + NX_WEBUI_LIST_INIT_TEXT_3 + '</div>';
KICA_CERTLISTEMPTY += '</th>';
KICA_CERTLISTEMPTY += '<th scope=\"col\">';
KICA_CERTLISTEMPTY += '<div>' + NX_WEBUI_LIST_INIT_TEXT_4 + '</div>';
KICA_CERTLISTEMPTY += '</th>';
KICA_CERTLISTEMPTY += '</tr>';
KICA_CERTLISTEMPTY += '</thead>';
KICA_CERTLISTEMPTY += '<tbody id=\"NXcertList\">';
KICA_CERTLISTEMPTY += '<tr id="certification01" onclick="NX_Issue_pubUi.certSelectRow_CertList(0);">';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '</tr>';
KICA_CERTLISTEMPTY += '<tr id="certification02" onclick="NX_Issue_pubUi.certSelectRow_CertList(1);" class=\"even\">';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '</tr>';
KICA_CERTLISTEMPTY += '<tr id="certification03" onclick="NX_Issue_pubUi.certSelectRow_CertList(2);">';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '</tr>';
KICA_CERTLISTEMPTY += '<tr id="certification04" onclick="NX_Issue_pubUi.certSelectRow_CertList(3);" class=\"even\">';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '</tr>';
KICA_CERTLISTEMPTY += '<tr id="certification05" onclick="NX_Issue_pubUi.certSelectRow_CertList(4);">';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '<td>&nbsp;</td>';
KICA_CERTLISTEMPTY += '</tr>';
KICA_CERTLISTEMPTY += '</tbody>';
KICA_CERTLISTEMPTY += '</table>';
KICA_CERTLISTEMPTY += '</div>';


var KICA_SECUKITNXDIV = '';
KICA_SECUKITNXDIV += '<!-- KICA Web UI START :: A타입-->';
KICA_SECUKITNXDIV += '<div class=\"nx-pki-ui-wrapper\" id=\"nx-pki-ui-wrapper\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<!-- 인증서 선택창 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA nx-cert-select\" id=\"nx-cert-select\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class="pki-head2">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_SELECT_TEXT_2 + ' <a href="#" class="btn-setting" onclick="NX_Issue_pubUi.managemnetPageOpen(); NXClientGetVersion();">' + NX_WEBUI_SELECT_TEXT_1 + '</a> </h1>';
KICA_SECUKITNXDIV += '<!-- 추가 작업 : <a href=\"#\" class=\"btn-setting\">' + NX_WEBUI_SELECT_TEXT_1 + '</a>-->';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"logo-area\" id=\"nx-cert-select-logo-area\" style="line-height:0.7;"></div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit1\">' + NX_WEBUI_SELECT_TEXT_3 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"cert-location-area\">';
KICA_SECUKITNXDIV += '<div class=\"cert-location-area-select-media\" id=\"cert-location-area-select-media\"></div>';

//<!-- PIN 입력 창 추가 -->
KICA_SECUKITNXDIV += '<!-- PIN 입력창 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap6 typeA width260\">';
KICA_SECUKITNXDIV += '<div id=\"pki-extra-media-box3\">';
KICA_SECUKITNXDIV += '<div id=\"pki-extra-media-box-contents3\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head3\"><h1>' + NX_WEBUI_SELECT_TEXT_13 + '</h1><a href=\"#\" class=\"btn-close1\" onclick=\"NX_Issue_pubUi.moreSaveMediaHide5();return false;\"></a></div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom3\">';
KICA_SECUKITNXDIV += '<div class=\"gray-box2 mb10\"> ' + NX_WEBUI_SELECT_TEXT_14 + ' </div>';
KICA_SECUKITNXDIV += '<input id="nx_cert_pin" name="nx_cert_pin"  type="password" size=20>';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick="NX_Issue_pubUi.moreSaveMediaHide7();return false;">' + NX_WEBUI_SELECT_TEXT_15 + '</button>';
KICA_SECUKITNXDIV += '</div></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img3\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //PIN 입력창 -->';
//<!--// PIN 입력 창 추가 -->

KICA_SECUKITNXDIV += '<!-- 추가 매체선택창 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap3 typeA width260\">';
KICA_SECUKITNXDIV += '<div id=\"pki-extra-media-box3\">';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img3\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //추가 매체선택창 -->';
KICA_SECUKITNXDIV += '<!-- 갱신 안내 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap5 typeA width280\" id=\"nx-error-cert-update\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head5\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_SELECT_TEXT_4 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div id=\"nx-error-cert-update-msg-box\"></div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img5\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- // 갱신 안내 -->';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<h2 class=\"tit1\">' + NX_WEBUI_SELECT_TEXT_5 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"cert-select-area\">';
KICA_SECUKITNXDIV += '<input type=\"hidden\" id=\"certId\" value=\"\">';
KICA_SECUKITNXDIV += '<div id=\"select-cert-list\" class=\"select-cert-list\">';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"cert-button-block\">';
KICA_SECUKITNXDIV += '<!--<button type=\"button\">인증서 찾기</button>-->';
KICA_SECUKITNXDIV += '<button type=\"button\" onclick=\"NX_Issue_pubUi.viewCertInfo();\">' + NX_WEBUI_SELECT_TEXT_7 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<h2 class=\"tit1\" id=\"pwdnoti_1\">' + NX_WEBUI_SELECT_TEXT_8 + '</h2>';

KICA_SECUKITNXDIV += '<form name=\"formRe\" id=\"formReId\" method=\"post\" action=\"javascript:NX_Issue_pubUi.selectCertConfirm();\">';
KICA_SECUKITNXDIV += '<div class=\"cert-password-area\">';

if (NOS_F === true) {
    //잉카 키보드보안 연동을 위한 수정
    KICA_SECUKITNXDIV += '<input type=\"password\" id=\"certPwd\" name=\"RePwName\" npkencrypt=\"Sub\" style=\"width: 100%;\" />';
}
else if (RAON_F === true) {
    //라온시큐어 키보드보안 연동을 위한 수정
    KICA_SECUKITNXDIV += '<input type=\"password\" id=\"certPwd\" name=\"certPwd\" style=\"width: 100%;\"  data-enc=\"on\"/>';
}
else {
    KICA_SECUKITNXDIV += '<input type=\"password\" id=\"certPwd\" style=\"width: 100%;\" />';
}

KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</form>';
KICA_SECUKITNXDIV += '<p class=\"noti\" id=\"pwdnoti_2\">' + NX_WEBUI_SELECT_TEXT_9 + '</p>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.selectCertConfirm();\">' + NX_WEBUI_DETAIL_INFO_TEXT_1 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.selectCertCancel();\">' + NX_WEBUI_DETAIL_INFO_TEXT_2 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 선택창 -->';

KICA_SECUKITNXDIV += '<!-- 인증서 정보창 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-detail-info\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_DETAIL_INFO_TEXT_3 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<ul class=\"pki-tab\">';
KICA_SECUKITNXDIV += '<li><a href=\"#certContent_01\" class=\"on\" onclick=\"NX_Issue_pubUi.certTabClick(this);return false;\">' + NX_WEBUI_DETAIL_INFO_TEXT_4 + '</a></li>';
KICA_SECUKITNXDIV += '</ul>';
KICA_SECUKITNXDIV += '<div class=\"pki-tab-con\">';
KICA_SECUKITNXDIV += '<div id=\"certContent_01\" class=\"cert-content\" style="display: block;">';
KICA_SECUKITNXDIV += '<h2 class=\"cert-tit\">' + NX_WEBUI_DETAIL_INFO_TEXT_4 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"cert-info-box3\">';
KICA_SECUKITNXDIV += '<div id=\"certContent_01_box\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.viewCertInfoConfirm();\">' + NX_WEBUI_DETAIL_INFO_TEXT_5 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 정보창 -->';

KICA_SECUKITNXDIV += '<!-- 인증서 관리창 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-managemnet\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_MANAGEMENT_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<ul class=\"pki-tab\">';
KICA_SECUKITNXDIV += '<li><a href=\"#certContent_02\" class=\"on\" onclick=\"NX_Issue_pubUi.certTabClick(this);return false;\">' + NX_WEBUI_MANAGEMENT_TEXT_2 + '</a></li>';
if (CERTMGR_F === true) {
    KICA_SECUKITNXDIV += '<li><a href=\"#certContent_03\" onclick=\"NX_Issue_pubUi.certTabClick(this); return false;\">' + NX_WEBUI_MANAGEMENT_TEXT_3 + '</a></li>';   //인증서 관리
}
KICA_SECUKITNXDIV += '</ul>';
KICA_SECUKITNXDIV += '<div class=\"pki-tab-con\">';
KICA_SECUKITNXDIV += '<div id=\"certContent_02\" class=\"cert-content\" style="display: block;">';

KICA_SECUKITNXDIV += '<h2 class=\"cert-tit\">' + NX_WEBUI_MANAGEMENT_TEXT_4 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"cert-info-box\">';
KICA_SECUKITNXDIV += '<p>' + NX_WEBUI_MANAGEMENT_TEXT_5 + '';
KICA_SECUKITNXDIV += '<p>';
KICA_SECUKITNXDIV += '<dl>';
KICA_SECUKITNXDIV += '<dt>KISA RootCA 1 (RSA)</dt>';
KICA_SECUKITNXDIV += '<dd>6FDB : 3F76 : C8B8 : 01A7 : 5338 : D8A5 : 0A7C : 0287 : 9F61 : 98B5 : 7E59 : 4D31 : 8D38 : 3290 : 0FED : CD79</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '<dl>';
KICA_SECUKITNXDIV += '<dt>KISA RootCA 4 (RSA)</dt>';
KICA_SECUKITNXDIV += '<dd>A002 : FF55 : 6C60 : 1863 : B08B : 9AA3 : 3A8E : 6666 : E97E : 72BB : E552 : F66E : B9F2 : 395C : 68C7 : BC98</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '<p class=\"go-link\"><a href=\"http://rootca.kisa.or.kr/kor/popup/potency.jsp\" target=\"_blank\">' + NX_WEBUI_MANAGEMENT_TEXT_9 + '</a></p>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<br/>';
KICA_SECUKITNXDIV += '<br/>';
KICA_SECUKITNXDIV += '<h2 class=\"cert-tit\">' + NX_WEBUI_MANAGEMENT_TEXT_14 + '</h2>';
KICA_SECUKITNXDIV += '<p>';
KICA_SECUKITNXDIV += '<div class=\"version-box\"><p id=\"client-version\"></p></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div id=\"certContent_03\" class=\"cert-content\">';
KICA_SECUKITNXDIV += '<div class=\"cert-info-box2\">';
KICA_SECUKITNXDIV += '<ul>';
KICA_SECUKITNXDIV += '<li><span>' + NX_WEBUI_MANAGEMENT_TEXT_10 + '</span>';
KICA_SECUKITNXDIV += '<button type=\"button\" class=\"btn-style1\" onclick=\"NX_Issue_pubUi.exportPFX();\">' + NX_WEBUI_MANAGEMENT_TEXT_11 + '</button>';
KICA_SECUKITNXDIV += '</li>';
KICA_SECUKITNXDIV += '<li><span>' + NX_WEBUI_MANAGEMENT_TEXT_12 + '</span>';
KICA_SECUKITNXDIV += '<button type=\"button\" class=\"btn-style1\" onclick=\"NX_Issue_pubUi.importPFX();\">' + NX_WEBUI_MANAGEMENT_TEXT_13 + '</button>';
KICA_SECUKITNXDIV += '</li>';
KICA_SECUKITNXDIV += '</ul>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.managemnetPageOpenConfirm();\">' + NX_WEBUI_MANAGEMENT_TEXT_15 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 관리창 -->';


KICA_SECUKITNXDIV += '<!-- 인증서 내보내기-1 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-management-exportPFX-fileName\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_EX_PFX_FILE_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_EX_PFX_FILE_TEXT_2 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<input type=\"text\" name=\"exportP12Name\" id=\"exportP12Name\" size=\"20\"><br />';
KICA_SECUKITNXDIV += '<p>' + NX_WEBUI_EX_PFX_FILE_TEXT_3 + '</p>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.exportPFXFileNameConfirm();\">' + NX_WEBUI_EX_PFX_FILE_TEXT_4 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.exportPFXFileNameCancel();\">' + NX_WEBUI_EX_PFX_FILE_TEXT_5 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 내보내기-1 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 내보내기-2 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-management-exportPFX-withKm\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_EX_PFX_KM_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_EX_PFX_KM_TEXT_2 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"\">';
KICA_SECUKITNXDIV += '<ul class=\"bul-list-dot\">';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_EX_PFX_KM_TEXT_3 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_EX_PFX_KM_TEXT_4 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_EX_PFX_KM_TEXT_5 + '</li>';
KICA_SECUKITNXDIV += '</ul>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"gray-box2 mt30 mb30\">';
KICA_SECUKITNXDIV += '<dl class=\"dl-style1 radio\">';
KICA_SECUKITNXDIV += '<dt>' + NX_WEBUI_EX_PFX_KM_TEXT_6 + '</dt>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"keyName\" id=\"exportWithKm\"/>';
KICA_SECUKITNXDIV += '' + NX_WEBUI_EX_PFX_KM_TEXT_7 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"keyName\" id=\"exportWithoutKm\"/>';
KICA_SECUKITNXDIV += '' + NX_WEBUI_EX_PFX_KM_TEXT_8 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_EX_PFX_KM_TEXT_13 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"\">';
KICA_SECUKITNXDIV += '<ul class=\"bul-list-dot\">';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_EX_PFX_KM_TEXT_9 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_EX_PFX_KM_TEXT_10 + '</li>';
KICA_SECUKITNXDIV += '</ul>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.exportPFXWithKmConfirm();\">' + NX_WEBUI_EX_PFX_KM_TEXT_11 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.exportPFXWithKmCancel();\">' + NX_WEBUI_EX_PFX_KM_TEXT_12 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 내보내기-2 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 가져오기-1 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-management-importPFX\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_IMP_PFX_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<dl class=\"dl-style1\">';
KICA_SECUKITNXDIV += '<dt>' + NX_WEBUI_IMP_PFX_TEXT_2 + '</dt>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<div class=\"file-type-wrap w75\">';
KICA_SECUKITNXDIV += '<input type=\"text\" readonly=\"readonly\"title=\"' + NX_WEBUI_IMP_PFX_TEXT_3 + '\" id=\"importPFXFileName\"/>';
KICA_SECUKITNXDIV += '<span class=\"btn-file\">';
KICA_SECUKITNXDIV += '<button class=\"btn-style1\" onclick=\"NXGetPFXFilePath();\">' + NX_WEBUI_IMP_PFX_TEXT_5 + '</button>';
KICA_SECUKITNXDIV += '</span> </div>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '<dl class=\"dl-style1\">';
KICA_SECUKITNXDIV += '<dt>' + NX_WEBUI_IMP_PFX_TEXT_6 + '</dt>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<input type=\"password\" id=\"importPFXPwd\" style=\"width:239px;\" />';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.importPFXConfirm();\">' + NX_WEBUI_IMP_PFX_TEXT_7 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.importPFXCancel();\">' + NX_WEBUI_IMP_PFX_TEXT_8 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 가져오기-1 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 폐지-1 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\"  style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_ABOLISH1_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<div class=\"bg-img-area\"><img src=\"' + NX_DEFAULT_IMG_URL + 'img_revoke.png\" alt=\"\" /></div>';
KICA_SECUKITNXDIV += '<div class=\"gray-box2\">';
KICA_SECUKITNXDIV += '<p class=\"txt-c\"><span class=\"inline-tit\">' + NX_WEBUI_ABOLISH1_TEXT_2 + '</span></p>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"\">' + NX_WEBUI_ABOLISH1_TEXT_3 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"\">' + NX_WEBUI_ABOLISH1_TEXT_4 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 폐지-1 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 폐지-2 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\"  style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_ABOLISH2_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_ABOLISH2_TEXT_2 + ' <strong class=\"red\">' + NX_WEBUI_ABOLISH2_TEXT_3 + '</strong>' + NX_WEBUI_ABOLISH2_TEXT_4 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<dl class=\"dl-style1 radio\">';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"revokeReason\" id=\"revokeReason_Km\" />';
KICA_SECUKITNXDIV += '' + NX_WEBUI_ABOLISH2_TEXT_5 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"revokeReason\" id=\"revokeReason_reName\"/>';
KICA_SECUKITNXDIV += '' + NX_WEBUI_ABOLISH2_TEXT_6 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"revokeReason\" id=\"revokeReason_noUse\"/>';
KICA_SECUKITNXDIV += '' + NX_WEBUI_ABOLISH2_TEXT_7 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"\">' + NX_WEBUI_ABOLISH2_TEXT_8 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"\">' + NX_WEBUI_ABOLISH2_TEXT_9 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 폐지-2 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 비밀번호 변경 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\"  style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_CHANGE_PWD_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '	<p class=\"txt2\">' + NX_WEBUI_CHANGE_PWD_TEXT_2 + '</p>';
KICA_SECUKITNXDIV += '<p class=\"txt2\">' + NX_WEBUI_CHANGE_PWD_TEXT_3 + '</p>';
KICA_SECUKITNXDIV += '<div class=\"gray-box mb30\">';
KICA_SECUKITNXDIV += '<table class=\"tbl-style\">';
KICA_SECUKITNXDIV += '<caption>';
KICA_SECUKITNXDIV += '</caption>';
KICA_SECUKITNXDIV += '<colgroup>';
KICA_SECUKITNXDIV += '<col style=\"width:170px;\" />';
KICA_SECUKITNXDIV += '</colgroup>';
KICA_SECUKITNXDIV += '<tbody>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_WEBUI_CHANGE_PWD_TEXT_4 + '</th>';
KICA_SECUKITNXDIV += '<td><input type=\"password\" id=\"makeNewPwd\"/></td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_WEBUI_CHANGE_PWD_TEXT_5 + '</th>';
KICA_SECUKITNXDIV += '<td><input type=\"password\" id=\"makeNewPwdConfirm\"/></td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '</tbody>';
KICA_SECUKITNXDIV += '</table>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_CHANGE_PWD_TEXT_6 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"\">';
KICA_SECUKITNXDIV += '<ol class=\"decimal\">';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_CHANGE_PWD_TEXT_7 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_CHANGE_PWD_TEXT_8 + '<br />';
KICA_SECUKITNXDIV += '' + NX_WEBUI_CHANGE_PWD_TEXT_9 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_WEBUI_CHANGE_PWD_TEXT_10 + '<br />';
KICA_SECUKITNXDIV += '' + NX_WEBUI_CHANGE_PWD_TEXT_11 + '<br />';
KICA_SECUKITNXDIV += '' + NX_WEBUI_CHANGE_PWD_TEXT_12 + '</li>';
KICA_SECUKITNXDIV += '</ol>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"\">' + NX_WEBUI_CHANGE_PWD_TEXT_13 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"\">' + NX_WEBUI_CHANGE_PWD_TEXT_14 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 비밀번호 변경 --> ';

KICA_SECUKITNXDIV += '<!-- 신원확인 식별번호 입력 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-VerifyIdentify\"  style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_INPUT_IDN_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<p class=\"txt2\">' + NX_WEBUI_INPUT_IDN_TEXT_2 + '</p>';
KICA_SECUKITNXDIV += '<p class=\"txt2\">' + NX_WEBUI_INPUT_IDN_TEXT_3 + '</p>';
KICA_SECUKITNXDIV += '<div class=\"gray-box mb30\">';
KICA_SECUKITNXDIV += '<table class=\"tbl-style\">';
KICA_SECUKITNXDIV += '<caption>';
KICA_SECUKITNXDIV += '</caption>';
KICA_SECUKITNXDIV += '<colgroup>';
KICA_SECUKITNXDIV += '<col style=\"width:140px;\" />';
KICA_SECUKITNXDIV += '</colgroup>';
KICA_SECUKITNXDIV += '<tbody>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_WEBUI_INPUT_IDN_TEXT_4 + '</th>';
KICA_SECUKITNXDIV += '<td><input type=\"password\" id=\"chkSSN\"/></td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '</tbody>';
KICA_SECUKITNXDIV += '</table>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.VerifyIdentifyConfirm();\">' + NX_WEBUI_INPUT_IDN_TEXT_5 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.VerifyIdentifyCancel();\">' + NX_WEBUI_INPUT_IDN_TEXT_6 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //신원확인 식별번호 입력 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 복사 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-copy-duplication\"  style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_COPY_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\"><strong class=\"red\">' + NX_WEBUI_COPY_TEXT_2 + '</strong><strong>' + NX_WEBUI_COPY_TEXT_3 + '</strong>' + NX_WEBUI_COPY_TEXT_4 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<dl class=\"dl-style1 radio\">';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"certCopy\" id=\"certChangeYes\" />';
KICA_SECUKITNXDIV += '' + NX_WEBUI_COPY_TEXT_5 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<label>';
KICA_SECUKITNXDIV += '<input type=\"radio\" name=\"certCopy\" id=\"certChangeNo\"/>';
KICA_SECUKITNXDIV += '' + NX_WEBUI_COPY_TEXT_6 + '</label>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.copyCertDuplicationConfirm();\">' + NX_WEBUI_COPY_TEXT_7 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.copyCertDuplicationCancel();\">' + NX_WEBUI_COPY_TEXT_8 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 복사 --> ';

KICA_SECUKITNXDIV += '<!-- 인증서 비밀번호 확인 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-checkPassword\"  style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_CHK_PW_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<div class=\"bg-img-area\"><img src=\"' + NX_DEFAULT_IMG_URL + 'img_pwok.png\" alt=\"\" /></div>';
KICA_SECUKITNXDIV += '<div class=\"gray-box2\">';
KICA_SECUKITNXDIV += '<p class=\"txt-c\"><span class=\"inline-tit\">' + NX_WEBUI_CHK_PW_2 + '</span></p>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.checkPasswordConfirm();\">' + NX_WEBUI_CHK_PW_3 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 비밀번호 확인 --> ';


KICA_SECUKITNXDIV += '<!-- 매체 선택 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-targetMedia-select\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_MEDIA_SELECT_TEXT_1 + '<span>' + NX_MEDIA_SELECT_TEXT_2 + '</span></h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"logo-area\" id=\"nx-targetMedia-select-logo-area\" style=\"height:99px;\"></div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit1\">' + NX_MEDIA_SELECT_TEXT_3 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"cert-location-area\">';
KICA_SECUKITNXDIV += '<div class=\"cert-location-area-targetMedia\" id=\"cert-location-area-targetMedia\"></div>';
KICA_SECUKITNXDIV += '<!-- 추가 매체선택창 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap4 typeA width260\">';
KICA_SECUKITNXDIV += '<div id=\"pki-extra-media-box4\"></div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img4\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- 추가 매체선택창 -->';
KICA_SECUKITNXDIV += '<div class=\"noti-box\">';
KICA_SECUKITNXDIV += '<p class=\"noti-txt\" id=\"targetMedia_noti\">' + NX_MEDIA_SELECT_TEXT_4 + '</p>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.selectMediaConfirm();\">' + NX_MEDIA_SELECT_TEXT_5 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.selectMediaCancel();\">' + NX_MEDIA_SELECT_TEXT_6 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //매체 선택 -->';

KICA_SECUKITNXDIV += '<!-- 인증서 발급 -->';
KICA_SECUKITNXDIV += '<!--<div class=\"pki-wrap typeA\" id=\"nx-retCode-insert\" >';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_RETCODE_INSERT_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_RETCODE_INSERT_TEXT_2 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<table class=\"tbl-style\">';
KICA_SECUKITNXDIV += '<caption>';
KICA_SECUKITNXDIV += '</caption>';
KICA_SECUKITNXDIV += '<colgroup>';
KICA_SECUKITNXDIV += '<col style=\"width:70px;\" />';
KICA_SECUKITNXDIV += '</colgroup>';
KICA_SECUKITNXDIV += '<tbody>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_RETCODE_INSERT_TEXT_3 + '</th>';
KICA_SECUKITNXDIV += '<td><input type=\"text\" name=\"nx_authCode\" id=\"nx_authCode\" placeholder=\"' + NX_RETCODE_INSERT_TEXT_4 + '\" /></td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_RETCODE_INSERT_TEXT_5 + '</th>';
KICA_SECUKITNXDIV += '<td><input type=\"text\" name=\"nx_refCode\" id=\"nx_refCode\" placeholder=\"' + NX_RETCODE_INSERT_TEXT_6 + '\" /></td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '</tbody>';
KICA_SECUKITNXDIV += '</table>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\">' + NX_RETCODE_INSERT_TEXT_7 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\">' + NX_RETCODE_INSERT_TEXT_8 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>-->';
KICA_SECUKITNXDIV += '<!-- //인증서 발급 -->';

KICA_SECUKITNXDIV += '<!-- 인증서 암호입력 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-pwd-insert\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_PWD_INSERT_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<p class=\"txt2\">' + NX_PWD_INSERT_TEXT_2 + '</p>';
KICA_SECUKITNXDIV += '<p class=\"txt2\">' + NX_PWD_INSERT_TEXT_3 + '</p>';
KICA_SECUKITNXDIV += '<div class=\"gray-box mb30\">';
KICA_SECUKITNXDIV += '<table class=\"tbl-style\">';
KICA_SECUKITNXDIV += '<caption>';
KICA_SECUKITNXDIV += '</caption>';
KICA_SECUKITNXDIV += '<colgroup>';
KICA_SECUKITNXDIV += '<col style=\"width: 120px;\" />';
KICA_SECUKITNXDIV += '</colgroup>';
KICA_SECUKITNXDIV += '<tbody>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_PWD_INSERT_TEXT_1 + '</th>';
KICA_SECUKITNXDIV += '<td>';
KICA_SECUKITNXDIV += '<input type=\"password\" name=\"nx_issue_cert_pw\" id=\"nx_issue_cert_pw\" /></td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '<tr>';
KICA_SECUKITNXDIV += '<th>' + NX_PWD_INSERT_TEXT_4 + '</th>';
KICA_SECUKITNXDIV += '<td>';
KICA_SECUKITNXDIV += '<form action=\"javascript:NX_Issue_pubUi.insertPWConfirm();\">';
KICA_SECUKITNXDIV += '<input type=\"password\" name=\"nx_issue_cert_pw_confirm\" id=\"nx_issue_cert_pw_confirm\" />';
KICA_SECUKITNXDIV += '</form>';
KICA_SECUKITNXDIV += '</td>';
KICA_SECUKITNXDIV += '</tr>';
KICA_SECUKITNXDIV += '</tbody>';
KICA_SECUKITNXDIV += '</table>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_PWD_INSERT_TEXT_5 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"\">';
KICA_SECUKITNXDIV += '<ol class=\"decimal\">';
KICA_SECUKITNXDIV += '<li>' + NX_PWD_INSERT_TEXT_6 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_PWD_INSERT_TEXT_7 + '<br />';
KICA_SECUKITNXDIV += '' + NX_PWD_INSERT_TEXT_8 + '</li>';
KICA_SECUKITNXDIV += '<li>' + NX_PWD_INSERT_TEXT_9 + '<br />';
KICA_SECUKITNXDIV += '' + NX_PWD_INSERT_TEXT_10 + '<br />';
KICA_SECUKITNXDIV += '' + NX_PWD_INSERT_TEXT_11 + '</li>';
KICA_SECUKITNXDIV += '</ol>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.insertPWConfirm();\">' + NX_PWD_INSERT_TEXT_12 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.insertPWCancel();\">' + NX_PWD_INSERT_TEXT_13 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 암호입력 -->';

KICA_SECUKITNXDIV += '<!-- 보안토큰 비밀번호 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-secureToken-pin-insert\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_SECUTOKEN_PWD_TEXT_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<dl class=\"dl-style1\">';
KICA_SECUKITNXDIV += '<dt class=\"typ2\">' + NX_SECUTOKEN_PWD_TEXT_2 + '</dt>';
KICA_SECUKITNXDIV += '<dd>';
KICA_SECUKITNXDIV += '<form action=\"javascript:NX_Issue_pubUi.insertPINConfirm();\">';
KICA_SECUKITNXDIV += '<input type=\"password\" name=\"nx_issue_cert_pin\" id=\"nx_issue_cert_pin\" />';
KICA_SECUKITNXDIV += '</form>';
KICA_SECUKITNXDIV += '</dd>';
KICA_SECUKITNXDIV += '</dl>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.insertPINConfirm();\">' + NX_SECUTOKEN_PWD_TEXT_3 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.insertPINCancel();\">' + NX_SECUTOKEN_PWD_TEXT_4 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //보안토큰 비밀번호 -->';

KICA_SECUKITNXDIV += '<!-- 인증서 발급&재발급&갱신 중 알림 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-issue-ing-alert\" style=\"display: none; margin-top:10%;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\" id=\"nx-issue-ing-alert-head\">';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div id=\"loading_progress\"></div>';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\" id=\"nx-issue-ing-alert-box\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 발급&재발급&갱신 중 알림 -->';
KICA_SECUKITNXDIV += '<!-- 인증서 발급&재발급&갱신 성공 알림 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-issue-success-alert\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\" id=\"nx-issue-success-alert-head\">';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\" id=\"nx-issue-succes-alert-box\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.issueCertConfirm();\">' + NX_ISSUE_SUCCESS_ALERT_1 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 발급&재발급&갱신 성공 알림 -->';
KICA_SECUKITNXDIV += '<!-- 인증서 발급&재발급&갱신 실패 알림 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-issue-fail-alert\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\" id=\"nx-issue-fail-alert-head\">';
KICA_SECUKITNXDIV += '<!--<div class=\"nx-issue-fail-alert-head-msg\"></div>-->';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\" id=\"nx-issue-fail-alert-box\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.issueCertFailConfirm();\">' + NX_ISSUE_FAIL_ALERT_1 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 발급&재발급&갱신 실패 알림 -->';
KICA_SECUKITNXDIV += '<!-- 인증서 삭제 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-delete\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_DELETE_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_DELETE_2 + ' <strong class=\"red\">' + NX_WEBUI_DELETE_3 + '</strong>' + NX_WEBUI_DELETE_4 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<div id=\"nx-cert-delete-box\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.deleteCertConfirm();\">' + NX_WEBUI_DELETE_5 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.deleteCertCancel();\">' + NX_WEBUI_DELETE_6 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 삭제 -->';

KICA_SECUKITNXDIV += '<!-- 인증서 폐지 -->';
KICA_SECUKITNXDIV += '<div class=\"pki-wrap typeA\" id=\"nx-cert-revoke\" style=\"display: none;\">';
KICA_SECUKITNXDIV += '<div class=\"pki-head\">';
KICA_SECUKITNXDIV += '<h1>' + NX_WEBUI_REVOKE_1 + '</h1>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-body\">';
KICA_SECUKITNXDIV += '<div class=\"pki-con-wrap\">';
KICA_SECUKITNXDIV += '<h2 class=\"tit2\">' + NX_WEBUI_REVOKE_2 + ' <strong class=\"red\">' + NX_WEBUI_REVOKE_3 + '</strong>' + NX_WEBUI_REVOKE_4 + '</h2>';
KICA_SECUKITNXDIV += '<div class=\"gray-box\">';
KICA_SECUKITNXDIV += '<div id=\"nx-cert-revoke-box\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom\">';
KICA_SECUKITNXDIV += '<button class=\"btn-ok\" onclick=\"NX_Issue_pubUi.revokeCertConfirm();\">' + NX_WEBUI_REVOKE_5 + '</button>';
KICA_SECUKITNXDIV += '<button class=\"btn-cancel\" onclick=\"NX_Issue_pubUi.revokeCertCancel();\">' + NX_WEBUI_REVOKE_6 + '</button>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<div class=\"pki-bottom-img\"></div>';
KICA_SECUKITNXDIV += '</div>';
KICA_SECUKITNXDIV += '<!-- //인증서 폐지-->';
KICA_SECUKITNXDIV += '</div>';

// 클라이언트 로딩 전 화면 이벤트 차단을 위해 추가
KICA_SECUKITNXDIV += '<div id=\"nxs_loading_block\" class=\"nxs_loading_block\" style=\"display: none;\"></div>';

KICA_SECUKITNXDIV += '<!-- //KICA Web UI END :: 기본타입(시안B) -->';